@startuml class-diagram.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
boundary Showcase
control ContactController

User -> Showcase : "Click Contact"
Showcase -> ContactController : doContactUpdated()
ContactController -> Showcase : "Open window for update the contact"
Showcase -> User : "Displays window"
User -> Showcase : "Click Cancel"
Showcase -> ContactController : doEditContactCancelled()
ContactController -> Showcase : "Do nothing"
Showcase -> User : "Displays initial page"


@enduml
