@startuml Diagrama-Sequencia-Update.PNG
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
participant EditContactPresenter
participant ContractUpdateEvent
participant ContractController
participant ContactsPresenter

User -> EditContactPresenter : click on a contact
User <- EditContactPresenter : show the "update info" of the contact select

User -> EditContactPresenter : update the contact info
EditContactPresenter -> EditContactPresenter : blind();
EditContactPresenter -> EditContactPresenter : doSave();
EditContactPresenter -> ContractUpdateEvent : ContactUpdatedEvent(result);

ContractUpdateEvent -> ContractController : onContactUpdated();
ContractController -> ContactsPresenter : go(container);

ContactsPresenter -> ContactsPresenter : fetchContactDetails();
ContactsPresenter -> ContactsPresenter : sortContactDetails();

@enduml
